config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :items
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :price, numericality: { greater_than: 0, allow_nil: true }
  validates :name, presence: true

  after_initialize { p 'initialize' }
  after_save       { p 'save' }
  after_create     { p 'create' }
  after_update     { p 'update' }
  after_destroy    { p 'destroy' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  layout false
  skip_before_action :verify_authenticity_token

  def index
    @items = Item.all
  end

  def create
    item = Item.create(items_params)
    if item.persisted?
      redirect_to items_path
    else
      render json: item.errors, status: :unprocessable_entity
    end

  end

  def new

  end

  def show
    unless @item = Item.where(id: params[:id]).first
      render body: 'Page not found', status: 404
    end
  end

  def edit
    unless @item = Item.where(id: params[:id]).first
      render body: 'Page not found', status: 404
    end
  end

  def update
    item = Item.where(id: params[:id]).first
    if item.update(items_params)
      redirect_to item_path
    else
      render json: item.errors, status: :unprocessable_entity
    end
  end

  def destroy
    item = Item.where(id: params[:id]).first.destroy

    if item.destroyed?
      redirect_to items_path
    else
      render json: item.errors, status: :unprocessable_entity
    end
  end

  private

  def items_params
    params.permit(:name, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h2 style="color: #B00100; margin: 0 auto">edit <%= @item.name %></h2>

<%= form_tag item_path(@item), method: :put do %>
  <%= label_tag :name %>
  <%= text_field_tag :name, @item.name %>
  <%= label_tag :price %>
  <%= text_field_tag :price, @item.price %>
  <%= submit_tag "Update", class: "btn btn-large btn-primary" %>
<% end %>

app/views/items/index.html.erb
<h2 style="color: #B00100; margin: 0 auto">all items</h2> <br/>

<% @items.each do |item| %>
  <ul>
    <li><%= link_to item.name, item_path(item) %></li>
    <li><%= item.price %></li>
    <li><%= item.description %></li>
    <li><%= button_to('delete', item_path(item), method: :delete) %></li>
  </ul>
<% end %>

<br>

<%= link_to 'create new', new_item_path %>

app/views/items/new.html.erb
<h2 style="color: #B00100; margin: 0 auto">create new item</h2>

<%= form_tag items_path, method: :post do %>
  <%= label_tag :name %>
  <%= text_field_tag :name %>
  <%= label_tag :price %>
  <%= text_field_tag :price %>
  <%= submit_tag "Save", class: "btn btn-large btn-primary" %>
<% end %>

app/views/items/show.html.erb
<h2 style="color: #B00100; margin: 0 auto">show item</h2> <br/>

<h4><%= @item.name %></h4>

<ul>
  <li>Price: <%= @item.price %>$</li>
  <li>Description: <%= @item.description %></li>
  <li>Weight: <%= @item.weight %></li>
</ul>

<br>

<%= link_to "edit #{@item.name}", edit_item_path %>
<%= button_to("delete #{@item.name}", item_path(@item), method: :delete) %>
<%= link_to "index", items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCourse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>